site_url: https://courses.mlops.vn/
site_name: MLOpsVN
docs_dir: docs
theme:
  name: material
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
nav:
  - Home: index.md
  - Tổng quan hệ thống:
      - Giới thiệu: tong-quan-he-thong/gioi-thieu.md
      - Phân tích vấn đề: tong-quan-he-thong/phan-tich-van-de.md
  - PoC:
      - Định nghĩa PoC: poc/dinh-nghia-poc.md
      - Xây dựng PoC: poc/thuc-hien-poc.md
  - Xây dựng data pipeline:
      - Tổng quan pipeline: xay-dung-data-pipeline/tong-quan-pipeline.md
      - Data ingestion: xay-dung-data-pipeline/data-ingestion.md
      - Data cleaning: xay-dung-data-pipeline/data-cleaning.md
      - Data exploration & validation: xay-dung-data-pipeline/data-exploration-validation.md
  - Xây dựng training pipeline:
      - Tổng quan pipeline: xay-dung-training-pipeline/tong-quan-pipeline.md
      - Xây dựng pipeline: xay-dung-training-pipeline/xay-dung-pipeline.md
  - Triển khai model serving:
      - Tổng quan: trien-khai-model-serving/tong-quan.md
      - Thực hiện: trien-khai-model-serving/thuc-hien.md
  - Theo dõi hệ thống:
      - Tổng quan: theo-doi-he-thong/tong-quan.md
      - Theo dõi hệ thống: theo-doi-he-thong/theo-doi-he-thong.md
      - Theo dõi model: theo-doi-he-thong/theo-doi-model.md
      - Theo dõi data: theo-doi-he-thong/theo-doi-data.md
  - CI/CD:
      - Giới thiệu: ci-cd/gioi-thieu.md
      - Kiểm thử hệ thống: ci-cd/kiem-thu-he-thong.md
      - CI/CD cho data pipeline: ci-cd/data-pipeline.md
      - CI/CD cho training pipeline: ci-cd/training-pipeline.md
      - CI/CD cho model serving: ci-cd/model-serving.md
  - Tổng kết:
      - Tóm tắt nội dung: tong-ket/tom-tat-noi-dung.md
      - Một số vấn đề khác: tong-ket/mot-so-van-de-khac.md

copyright: "Copyright 2022 MLOpsVN Community. All Rights Reserved. Licensed under the Creative Commons Attribution 4.0 International Public License"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mlopsvn/courses.mlops.vn
