site_url: https://courses.mlops.vn/
site_name: MLOpsVN Courses
docs_dir: docs
theme:
    name: material
    features:
      - content.code.annotate
extra_css: [assets/stylesheets/styles.css]
plugins:
    - glightbox:
          touchNavigation: true
          loop: false
          effect: zoom
          width: 100%
          height: auto
          zoomable: true
          draggable: true
    - section-index
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
    - Home: index.md
    - MLOps Crash Course:
          - mlops-crash-course/index.md
          - Tổng quan hệ thống:
                - Phân tích vấn đề: mlops-crash-course/tong-quan-he-thong/phan-tich-van-de.md
                - MLOps platform: mlops-crash-course/tong-quan-he-thong/mlops-platform.md
          - PoC:
                - Định nghĩa PoC: mlops-crash-course/poc/dinh-nghia-poc.md
<<<<<<< HEAD
                - Xây dựng PoC: mlops-crash-course/poc/thuc-hien-poc.md
          - Data pipeline:
                - Tổng quan pipeline: mlops-crash-course/data-pipeline/tong-quan-data-pipeline.md
                - Airflow cơ bản: mlops-crash-course/data-pipeline/airflow-co-ban.md
                - Feature store: mlops-crash-course/data-pipeline/feature-store.md
                - Xây dựng data pipeline: mlops-crash-course/data-pipeline/xay-dung-data-pipeline.md
=======
                - Xây dựng PoC: mlops-crash-course/poc/xay-dung-poc.md
          - Xây dựng data pipeline:
                - Tổng quan pipeline: mlops-crash-course/xay-dung-data-pipeline/tong-quan-pipeline.md
                - Data ingestion: mlops-crash-course/xay-dung-data-pipeline/data-ingestion.md
                - Data cleaning: mlops-crash-course/xay-dung-data-pipeline/data-cleaning.md
                - Data exploration & validation: mlops-crash-course/xay-dung-data-pipeline/data-exploration-validation.md
>>>>>>> 11aee505ba8ae4a17f3d10d825c41fd8407998a4
          - Xây dựng training pipeline:
                - Tổng quan pipeline: mlops-crash-course/xay-dung-training-pipeline/tong-quan-pipeline.md
                - Xây dựng pipeline: mlops-crash-course/xay-dung-training-pipeline/xay-dung-pipeline.md
          - Triển khai model serving:
                - Tổng quan: mlops-crash-course/trien-khai-model-serving/tong-quan.md
                - Thực hiện: mlops-crash-course/trien-khai-model-serving/thuc-hien.md
          - Theo dõi hệ thống:
                - Tổng quan: mlops-crash-course/theo-doi-he-thong/tong-quan.md
                - Theo dõi hệ thống: mlops-crash-course/theo-doi-he-thong/theo-doi-he-thong.md
                - Theo dõi model: mlops-crash-course/theo-doi-he-thong/theo-doi-model.md
                - Theo dõi data: mlops-crash-course/theo-doi-he-thong/theo-doi-data.md
          - CI/CD:
                - Giới thiệu: mlops-crash-course/ci-cd/gioi-thieu.md
                - Kiểm thử hệ thống: mlops-crash-course/ci-cd/kiem-thu-he-thong.md
                - CI/CD cho data pipeline: mlops-crash-course/ci-cd/data-pipeline.md
                - CI/CD cho training pipeline: mlops-crash-course/ci-cd/training-pipeline.md
                - CI/CD cho model serving: mlops-crash-course/ci-cd/model-serving.md
          - Tổng kết:
                - Tóm tắt nội dung: mlops-crash-course/tong-ket/tom-tat-noi-dung.md
                - Một số vấn đề khác: mlops-crash-course/tong-ket/mot-so-van-de-khac.md
          - Contributing: CONTRIBUTING.md
          - Code of Conduct: CODE_OF_CONDUCT.md

copyright: "Copyright 2022 MLOpsVN Community. All Rights Reserved. Licensed under the Creative Commons Attribution 4.0 International Public License"
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/mlopsvn/courses.mlops.vn
